{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "entra-local.serviceAccountName" . }}
  labels:
    {{- include "entra-local.labels" . | nindent 4 }}
{{- end }}
